## Docker 容器 Mysql 8.0.12 环境配置
##
## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: dmego
    password: dmego
    url: jdbc:mysql://47.94.252.154:3307/odsp?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true

## 日志配置
#logging:
#    file: odsp-dev.log
#    level:
#        root: warn
#        cn.dme