## 端口
server:
  port: 8080


## 模板引擎 Beetl 配置
beetl:
    suffix: html
beetlsql:
    enabled: false

spring:
  ## 多环境配置
  profiles:
    active: dev
  ## json 时间格式设置
  ## 这里不能用“-”，必须用“/”，因为js的new Date()方法ie不支持“-”会出现NaN
  jackson:
    time-zone: GMT+8
    date-format: yyyy/MM/dd HH:mm:ss
  ## druid 连接池配置
  datasource:
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 30000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        validation-query: SELECT 'x'
        remove-abandoned: true
        remove-abandoned-timeout: 1800
        filters: stat,wall #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        aop-patterns: cn.dmego.odsp.*.service.*
        stat-view-servlet:
          url-pattern: /druid/*
          reset-enable: true
          login-username: admin
          login-password: admin

## MyBatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: cn.dmego.odsp.*.model
  global-config:
    id-type: 0
    field-strategy: 1
    #是否使用下划线命名
    db-column-underline: true
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

